name: build and render

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-render-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: build
      run:
        mkdir build; cd build;
        cmake ..; make -j;

    - name: render
      run:
        cd build;
        ./smallpt-mlt;
